### ISSUE TITLE
Linux build instructions - Missing file sh cppstuff.sh

### ISSUE THREAD

**Issue by gateway** [akai-katto/dandere2x#113]
Per Linux build instructions 

> Open a terminal in the root folder of the cloned dandere2x project from GitHub and
> 
> sh cppstuff.sh
> Important: you have to be on the root folder of the project, you can verify it by running pwd and verifying it ends with “/dandere2x”
> 
> Note: this moves the binary to the default path for it to be.

Is this removed.. I cant find this file :/

**Comment by aka-katto** [comment]
Probably, I'll link tremex's instructions for it.

Thanks for reminding me to maintain the linux portion of d2x more

**Comment by NightMachinary** [comment]
Does this work on macOS?

**Comment by aka-katto** [comment]
> Does this work on macOS?

I don't believe so, since mac OS doesn't support waifu2x types (I think?)

If it does, d2x should work on a mac.
