### ISSUE TITLE
How can I change the path of the workspace?（GUI）

### ISSUE THREAD

**Issue by Fiend1019** [akai-katto/dandere2x#122]
![QQ图片20200502005900](https://user-images.githubusercontent.com/64277417/80824026-397bc700-8c10-11ea-808e-d454a37cb07d.png)

**Comment by AlexFlait** [comment]
I have the same question. How can I change cache folder location?

**Comment by AlexFlait** [comment]
I found a solution. You should watch this page:
https://github.com/aka-katto/dandere2x/issues/96

**Comment by Fiend1019** [comment]
> I found a solution. You should watch this page:
> #96

Thank you! But why can't I find this file?

**Comment by AlexFlait** [comment]
I find the file in "source code" program version, but i can`t start the .py file(can`t strat program on source code). So, I think we just need to wait for answer from developer.

**Comment by aka-katto** [comment]
Sorry for the slow response

I'm not sure what you're asking, but if you wish to change the cache location with the .exe version of the program, in the ```dandere2x_win32.yaml```, you need to change the workspace to somewhere different. In 1.8, it's set to not work out of the temp folder. 

```

  developer_settings:

    debug: false
    workspace: ..\workspace\default\ # path to the workspace folder (lots of files will be written here)
    dandere2x_cpp_dir: ..\externals\dandere2x_cpp.exe # path to dandere2x_cpp binary file
    workspace_use_temp: false
    gui_delete_workspace_after: false
    extension_type: .jpg
    bleed: 1
    quality_moving_ratio: 0.55
    step_size: 8

```

Edit ```workspace_use_temp``` to be false and set ```workspace``` to where you want the cache to be.

**Comment by Fiend1019** [comment]
I am sorry that my description is not clear enough. The version I use is **1.3.1**, and it only has a file named **dandere2x.json**, I did not find a file named **dandere2x_win32.yaml**. I tried to modify this file before, as shown in the picture, but it failed.
![QQ图片20200508201704](https://user-images.githubusercontent.com/64277417/81404915-31b8a700-9169-11ea-8317-8014f6713e07.png)

**Comment by AlexFlait** [comment]
I`m also has only dandere2x.json. And changing "workspace_use_temp" to false, and it`s failed too.
My json looks like:
"workspace_use_temp": "false",
      "gui_delete_workspace_after": false,
      "workspace": "D:\\Temp\\Dandere2x_Temp\\",

**Comment by aka-katto** [comment]
Sorry for the slow response - I'm hoping to be more active in my own repo.




> I am sorry that my description is not clear enough. The version I use is **1.3.1**, and it only has a file named **dandere2x.json**, I did not find a file named **dandere2x_win32.yaml**. I tried to modify this file before, as shown in the picture, but it failed.
> ![QQ图片20200508201704](https://user-images.githubusercontent.com/64277417/81404915-31b8a700-9169-11ea-8317-8014f6713e07.png)

Try putting a ```\``` after your workspace.

**Comment by aka-katto** [comment]
> I am also has only dandere2x.json. And changing "workspace_use_temp" to false, and it is failed too.
> My json looks like:
> "workspace_use_temp": "false",
> "gui_delete_workspace_after": false,
> "workspace": "D:\Temp\Dandere2x_Temp\",
> P.S. Folders named "Temp" and "Dandere2x_Temp" was created manually.

Are you running as administrator?

**Comment by AlexFlait** [comment]
> > I am also has only dandere2x.json. And changing "workspace_use_temp" to false, and it is failed too.
> > My json looks like:
> > "workspace_use_temp": "false",
> > "gui_delete_workspace_after": false,
> > "workspace": "D:\Temp\Dandere2x_Temp",
> > P.S. Folders named "Temp" and "Dandere2x_Temp" was created manually.
> 
> Are you running as administrator?

No, I`m not. When I try, it is crushed. It was after I press the upscale button, it`s crashed without any warnings or messages.
