### ISSUE TITLE
GUI doesn't display correctly on 4K screens

### ISSUE THREAD

**Issue by 123321mario** [akai-katto/dandere2x#138]
works fine on a 1080p screen but it looks like that on a 4k screen, the program works fine tho
![image](https://user-images.githubusercontent.com/33780173/89641083-33e9e900-d8b1-11ea-9f07-63c6539543e2.png)

**Comment by Tremeschin** [comment]
*cries in high res / dpi scaling

**Comment by MaximumWoahverdrive** [comment]
a workaround i found is as follows:

Right Click dandere2x.exe
Properties
Go to the Compatibility Tab
Click "Change high DPI settings" near the bottom
Tick "Override high DPI scaling behavior. Scaling performed by:"
and select "System" or "System (Enhanced)"
Click OK on both windows to save the setting

that's what worked for me on Win 10
