### ISSUE TITLE
super long startup

### ISSUE THREAD

**Issue by yggdrasil75** [akai-katto/dandere2x#142]
I have no idea what you are doing in the background before startup, but it takes 2-3 minutes to do it. could all gui components be loaded first, then whatever background tasks you need done while the user is "fiddling" with settings, before it begins upscaling?

**Comment by aka-katto** [comment]
This is a result pyinstaller. If you run it natively through python, it doesn't take nearly this long. Let me know if you want instructions on how to do this

**Comment by peepopoggers** [comment]
pls instructions
