### ISSUE TITLE
Problems with the 0.3.0b and what I would like you to add

### ISSUE THREAD

**Issue by CareBearsAICAL** [akai-katto/dandere2x#157]
Hi, I'm very happy with this new update, it repaired the one I wanted most, the grid!
Here I leave my new observations:

**Dandere2x 0.3.0b [The best version]**
✔ Leave the videos at very good resolution
✔ No grid problems (barely noticeable)
✔ No cornering problems
✔ Colors no longer look yellowish and blue
❌ You have the problem of blocks in color fading transitions
❌ The colors change a bit compared to the original video
➖ Remastering is a little slow but worthwhile
➖ Lose some detail with a denoise 2 and 3

**Dandere2x 2.1.5**
✔ Remastering is fast
✔ Leave the videos at very good resolution
✔ No cornering problems
❌ There is a very noticeable grid in the video
❌ You have the problem of blocks in color fading transitions
❌ The videos have yellowish and blue spots
❌ The colors change a bit compared to the original video
➖ A bit of detail is lost with a denoise 2 and 3

**Dandere2x 1.3.1**
✔ Remastering is fast
✔ No grid problems (barely noticeable)
✔ The problem of the blocks that stay in the frame has a solution
❌ Blurry videos don't look so good in resolution
❌ Has cornering problem
❌ The colors change a little bit compared to the original
❌ Many details of the video are missing

**### What would I like in a new version?**
### 1. To solve the problem of different lighting blocks in color fading transitions
[vulkan][s2][n3][b60][q99] / [vulkan][s2][n3][b10][q99]
![vlcsnap-2020-11-27-22h20m20s440](https://user-images.githubusercontent.com/72674815/100529319-08bf3880-31c5-11eb-9f24-4a207d234e12.png)
![vlcsnap-2020-11-28-22h00m34s078](https://user-images.githubusercontent.com/72674815/100529331-31473280-31c5-11eb-9108-d2e371547b7a.png)

When I remastered a video that had a color fade animation, it still had dark blocks in it, with a block of 10 you could see a lot of them. And with a block 60, to my surprise, I got a dark block in 1 frame, apparently a big block solves the problem 99%. This problem had been solved by changing the quality_moving_ratio to 100 in version 1.3.1 to 1.8, but from 0.1.9.4 it no longer works. In all versions, the larger the block, the less likely this bug is to occur. I think this problem is due to the sensitivity that the program has to detect if the block is different to keep it or not. It would be great a configuration in the interface to be able to change this parameter, it could also serve something with which it detects better the difference of illumination of each block or having to increase the sensitivity of the block comparison to change it. For now I will try to solve it temporarily with "Resolve"

### 2. Small details
Original
![image](https://user-images.githubusercontent.com/72674815/100529476-e2020180-31c6-11eb-9ec1-3fe8b20a458d.png)
[vulkan][s2][n0][b60][q99]     [vulkan][s2][n1][b60][q99]
![image](https://user-images.githubusercontent.com/72674815/100529433-7c157a00-31c6-11eb-8b11-40a9dec59d8b.png) ![image](https://user-images.githubusercontent.com/72674815/100529497-ef1ef080-31c6-11eb-9512-dfeeeb9a8ac2.png)
[vulkan][s2][n2][b60][q99]     [vulkan][s2][n3][b60][q99]
![image](https://user-images.githubusercontent.com/72674815/100529503-f9d98580-31c6-11eb-84f1-e0616f81ef0e.png) ![image](https://user-images.githubusercontent.com/72674815/100529508-02ca5700-31c7-11eb-8897-aae4226ce045.png)

This could be difficult to solve, as some detail must be sacrificed to improve the quality of the videos. I would like to see that somehow, the little details are not lost when using a high denoise. Because the videos look very good with a x3 denoise, much less detail is lost than 1.3.1, but they are still lost (you can see it in the purple bear's eyebrows). I find that the denoise x2 is almost identical to the x3 but a little more blurred (you can see it in the eyes of the blue bear), it would be great if the denoise x2 has another mechanism to not lose those little details and at the same time it looks very good. Because right now, I prefer the x3 to the x2, because they are identical but the x2 has a worse quality and so it doesn't have to be a filler, it could have some other experimental method.

### 3. Colors
Original / [vulkan][s2][n3][b60][q99]
![image](https://user-images.githubusercontent.com/72674815/100529704-fe9f3900-31c8-11eb-85b3-fcc850d2002b.png) ![image](https://user-images.githubusercontent.com/72674815/100529688-d6afd580-31c8-11eb-8fa6-46fe55846595.png)
I would like there to be a way for the colors not to change much compared to the original, there could be a way for the colors to be more accurate, but if it could make the quality worse, I prefer it to stay as it is, because it can be solved with some other editing program.

### 4. A queue for several videos
I don't know if this will be difficult to implement, I would like very much to not be so vigilant in processing another video. Just have the program when it is finished, clean up, wait about 5 seconds and then start processing the next video.

### 5. Turn off at the end
I don't know if it's difficult to implement, but I always use this program at night and it would be great if the PC could rest when I finish restarting.

### What would my ideal Dandere2x look like?

This is a concept I created from the GUI, which includes new functions and where the steps are in order.
![image](https://user-images.githubusercontent.com/72674815/100529964-2a232300-31cb-11eb-91f7-945cc0ec2f23.png)

The Quality Moving Ratio option would be in charge of the sensitivity to change the block for the new frame or not. I don't know if it is an option that has to be configured from the UI, this could serve to remove the bug of the blocks with dark color in exchange for a longer processing time, or if the error of the blocks is corrected would no longer be necessary. Image Quality, while lower, seems to cause more dark blocks.

I would appreciate an option to turn off the PC at the end, I would leave it 1 minute after the end of everything and check that the video was saved and complete, to avoid errors. If you can, there could be a warning within that minute to cancel the shutdown.

Now it comes over the video queue.
The idea is that you can add several videos directly from the "Select Video" option and these will be in the list on the right, you could also add them later or also one by one. When they are added the first one will be automatically selected and they can be selected in the list on the right, so they can have their own settings and also their own custom output.

Also each video will have a button in the list to remove it, I don't know if you can add a way to order the videos in the list with some arrows, but I don't see it very necessary for now.

In the list the name it will have would be that of the added video and not of the output, for better identification.

When adding a new video, it should have by default the settings of the last video in the list.

The Input and Output that will be displayed would be from the video that is selected. The video could not be changed, by pressing "Select Video" but it would be added to the list and the other can be deleted, or you could also add a change video button, which you should also check and change the name that is displayed in the list.

The "Use these settings for all videos" option will be useful for people who want to resize several videos in a row with the same settings.
This would work, if active, to copy all settings to the other videos except the Output, and update them when there is a change, so that they also change, in case the user switches to another video, for example, to change the output and keep the settings.
If the user disables the option after activating it, the videos that were, will be with the same configuration of the one that was open at that moment, the configuration of the other videos with the one that is open will no longer be updated and so the person could use that option to change the configuration of all the videos, then disable it and change some that do not want to have that configuration.

This option would not affect the multiprocessing mode, because it is a video that is being processed at the same time and not all of them.

When the program finishes a video, it should check that the video is in its place, that it is complete and wait about 10 seconds before continuing with the next one, so as to avoid failures. Check that you are with the respective configuration of the video to start resizing it.

I know this can be complicated, but maybe it can be added in a future version.

For now, I would like the problem of dark blocks in color fading transitions to be corrected. With some configuration within the code or some option that allows changing the sensitivity in the GUI.

PS: This is the design that I liked the most, although now that I've finished writing, the list would have looked good in the middle and the settings at the end, moving the two boxes at the bottom a little higher, and placing the "Upscale!" button at the bottom, leaving the list in the middle and reaching the bottom.

translated from Spanish with DeepL

**Comment by aka-katto** [comment]
Thanks for running 0.3.0b! When running it, I noticed that the issues you described were caused by me not fixing the GUI - and hence was avoidable. I'm really happy me catching this bug fixed your issues with the blocks being super noticeable - this was really rewarding to see. 

I also greatly appreciate the formatting of this post - it makes it really easy for me to read and follow. It gives me questions to think about as I make a series of improvements for a 3.0 to have. 

With a 3.0 now being worked on, this post is a perfect starting point on where to start implementing improvements. I will progressively update this page as I work towards a 3.0 testing feature, and let you know which make it in. 

The effort shown here in this post shows a large amount of commitment to the program, something that I greatly value.

**Comment by Tsubajashi** [comment]
i would also like to ask for an addition:
A progress bar, which gives clear information about how much it has already done in the GUI, or in the Terminal when multiprocessing is activated. I know its experimental, but I would honestly love that feature a lot.

**Comment by aka-katto** [comment]
> 
> 
> i would also like to ask for an addition:
> A progress bar, which gives clear information about how much it has already done in the GUI, or in the Terminal when multiprocessing is activated. I know its experimental, but I would honestly love that feature a lot.

In the 3.0 release, status's for each subthread / subvideo are properly printed to console now, which wasn't there in 0.3.1b

**Comment by Tsubajashi** [comment]
when i was on windows, testing the 3.0 release, i saw these improvements, thats good.
but i also found out about something spamming the console: 
![image](https://user-images.githubusercontent.com/21346945/103163683-8052a880-4801-11eb-8d84-3dd074d3b0f8.png)
Folder Path was "C:\Users\Administrator\Videos\NCOP2.mp4"
also:
- dandere2x fails to grab its stuff from the ffprobe command - and falls back to another command after a short while (that happens often, around 3 times before it stops doing that)
- after sometime, interpolation starts, but only if i switch the waifu2x-ncnn-vulkan folder with another release i grabbed elsewhere, the download externals one instantly crashed on me as if it wasnt able to make the first image, so i suspect waifu2x-ncnn crashing. a newer one worked though.
- "WARNING:dandere2x.dandere2xlib.wrappers.frame.frame:Caught Syntax error - trying again" happens often through the entirety of the interpolation, but seems to not be fucked by it. it continues

**Comment by aka-katto** [comment]
> when i was on windows, testing the 3.0 release, i saw these improvements, thats good.
> but i also found out about something spamming the console:
> ![image](https://user-images.githubusercontent.com/21346945/103163683-8052a880-4801-11eb-8d84-3dd074d3b0f8.png)
> Folder Path was "C:\Users\Administrator\Videos\NCOP2.mp4"
> also:
> 
>     * dandere2x fails to grab its stuff from the ffprobe command - and falls back to another command after a short while (that happens often, around 3 times before it stops doing that)
> 
>     * after sometime, interpolation starts, but only if i switch the waifu2x-ncnn-vulkan folder with another release i grabbed elsewhere, the download externals one instantly crashed on me as if it wasnt able to make the first image, so i suspect waifu2x-ncnn crashing. a newer one worked though.
> 
>     * "WARNING:dandere2x.dandere2xlib.wrappers.frame.frame:Caught Syntax error - trying again" happens often through the entirety of the interpolation, but seems to not be fucked by it. it continues

Addressing individually,

>     * dandere2x fails to grab its stuff from the ffprobe command - and falls back to another command after a short while (that happens often, around 3 times before it stops doing that)

This happens when the video selected isn't using the assumed meta-data container format, which is 
somewhat common it seems. As long as this doesn't crash, this is expected behaviour.

\> after sometime, interpolation starts, but only if i switch the waifu2x-ncnn-vulkan folder with another release i grabbed elsewhere, the download externals one instantly crashed on me as if it wasnt able to make the first image, so i suspect waifu2x-ncnn crashing. a newer one worked though.

This reminds me to update the binaries. Good call 

>     * "WARNING:dandere2x.dandere2xlib.wrappers.frame.frame:Caught Syntax error - trying again" happens often through the entirety of the interpolation, but seems to not be fucked by it. it continues

This is out of my control actually - it turns out windows-team fucked up numpy in their October release, breaking some compatibility - I was thinking of silencing this error since it's expected behaviour until windows fixes their issues, but I should make a comment about it in the post explaining why it's there.
