### ISSUE TITLE
Vulkan x1 Scale factor support

### ISSUE THREAD

**Issue by provalinf** [akai-katto/dandere2x#163]
Hi guys,
A small and very fast request, since Waifu-2x Vulkan supports scale factor x1 and x2, can you make it enable the x1 option in danderex to denoiser a video without changing its resolution?

Thanks a lot
Friendly!

**Comment by akai-katto** [comment]
I wasn't aware that waifu2x-ncnn-vulkan added 1x support. I will upload a new build tonight.

Thanks for letting me know

**Comment by akai-katto** [comment]
Updated as a patch 

https://github.com/akai-katto/dandere2x/releases/tag/3.0.1
