### ISSUE TITLE
Multiprocess is slower than singleprocess

### ISSUE THREAD

**Issue by Harutami** [akai-katto/dandere2x#172]
So I have been trying to upscale a clip using D2X. The clip is about 20 sec long and it seemed to be doing fine until this point:

![3](https://user-images.githubusercontent.com/58604290/104511899-ae9bfa80-55ed-11eb-8184-25396d99a898.png)

I have waited for 2 hours with nothing new. So then I checked if Dandere is doing something but Task Manager doesn't say so :/
![1](https://user-images.githubusercontent.com/58604290/104511949-bf4c7080-55ed-11eb-93ca-ae07f902fdc5.png)

And when I exited Dandere this error shows up. (It seems to be working but at the same time not? -> It is hung up at split_video2 but it crashed at split_video1?)
![4](https://user-images.githubusercontent.com/58604290/104512210-279b5200-55ee-11eb-8e33-8bf247c7fe33.png)

Oh, and it doesnt matter if I use caffe, conv-cpp or vulkan.

Idk should I wait even longer?

**Comment by Harutami** [comment]
I use the latest release from the zip and externals are downloaded.

**Comment by Harutami** [comment]
ok I've been trying to use D2X on multiprocess. I just tried on singleprocess and now it worked in 15 min. Idk why that is but now it works at least.
![1](https://user-images.githubusercontent.com/58604290/104514038-e7899e80-55f0-11eb-88f6-02fa85b692e6.png)

**Comment by akai-katto** [comment]
Can you share your computer specs? It might be the case that your computer cant run 3 dandere2x sessions at once, and that its actually slowing stuff down.

**Comment by Harutami** [comment]
Intel i5-7500 (4c 4t)
16 GB DDR4 3000
GTX 1060 6GB
Everything SSD

**Comment by akai-katto** [comment]
I'm taking a stab at this, and I'm not sure how python's multi-thread works, but I use a bunch of threads in dandere2x-single process, so 4c 4t might not be enough. For reference, there's an ffmpeg instance + dandere2x_cpp instance + 5 subthreads for each dandere2x process, so we might run into resource-allocation racing conditions by using the multi-process mode on your setup.

**Comment by Harutami** [comment]
Yeah that could be the problem indeed. Well, this just gave me another reason to buy the Ryzen 9 5900X lmao. Btw. I love your program! I wish I could participate in it in the future :)

Should I close this thread or keep open if you want to make optimizations?

**Comment by akai-katto** [comment]
I'll close it out here. For what it's worth, I'm on a 3900x right now :] and it's super satisfying seeing all the cores get used lmao.
