### ISSUE TITLE
[WinError 2] The system cant find the specified file; Version 3.0.3

### ISSUE THREAD

**Issue by Harutami** [akai-katto/dandere2x#179]
I wanted to test the new version 3.0.3. So I took the gif in the workplace folder and tried to run Dandere on it.

Before it even started the processing this Error came up:

[WinError 2] The system cant find the specified file
![1](https://user-images.githubusercontent.com/58604290/104859205-c5ab5700-5923-11eb-9e68-58b7fdd2bb70.png)
(Note that the Error is in German)

The process won't start after that. I think its the new opencv, but it could also be that something really is missing. (3.0.2 works fine, so just 3.0.3)

**Comment by akai-katto** [comment]
Did danderex_cpp.exe disappear?

**Comment by Harutami** [comment]
You mean in Task manager?

**Comment by Harutami** [comment]
Yep it worked after putting the danderex_cpp.exe and all the cyg... .dll in externals

But why wasn't it there? I even downloaded it from scratch and didn't just copy from 3.0.2

**Comment by akai-katto** [comment]
> 
> 
> Yep it worked after putting the danderex_cpp.exe and all the cyg... .dll in externals
> 
> But why wasn't it there? I even downloaded it from scratch and didn't just copy from 3.0.2

These patches are usually meant to overwrite the binary of the current release (i.e downloading 3.0 and installing 3.0.3 into the location), not intended to be a full-blown new release (this is my association of the word hot-patch at least). 

Glad we got it fixed though, I tested it on my system before hand
