### ISSUE TITLE
Testing needed: installer against False-positive virus claims?

### ISSUE THREAD

**Issue by Harutami** [akai-katto/dandere2x#182]
So as @akai-katto and users discovered, there is a warning poping up, that says:

Operation did not complete successfully because the file contains a virus or potentially unwanted software

when trying to start up Dandere. I believe the problem is that pyinstaller is not building it all as Windows wants it to be and maybe Windows will recognize by really installing it, that is has no viruses and such.
So, I created an installer for Dandere (my restyled version 3.0.2). I tested it and it worked (if you obviously follow instructions like running Dandere as administrator).

The thing is I do not get any warnings as stated before on my system, so I would need to get feedback if it still comes up. 

The installer is in the one release of my fork of Dandere: https://github.com/Harutami/dandere2x

If nothing changed, then I will close down this issue and delete the installer.

**Comment by akai-katto** [comment]
I did research into this, it seems that building pyinstaller using the binaries will help take away the false positives. Will report back when I gave it a try.

For what its worth, I tried compiling ```print("hello world")``` on a fresh windows install using pyinstaller, and it got marked as a trojan. Windows made a mistake on this one

**Comment by Harutami** [comment]
Well that is a bit unfortunate. I also asked some people I know and it may also be the --one-file argument with the current binaries, but yeah.

As it doesn't seem that my idea worked, I will delete the installer then.
