### ISSUE TITLE
don't know what i'm dsoing wrong

### ISSUE THREAD

**Issue by WrMatsuri** [akai-katto/dandere2x#193]
can someone help me ? 
![image](https://user-images.githubusercontent.com/69734768/107710097-9f7c9b00-6cc6-11eb-96f7-0cc887533549.png)

**Comment by akai-katto** [comment]
Were you the one who posted on reddit? Can you try the latest build,  not 2.0rc?

**Comment by WrMatsuri** [comment]
no it wasn't me, but thanks it work perfectly now!
