### ISSUE TITLE
My experience and how I use Dandere2x

### ISSUE THREAD

**Issue by CareBearsAICAL** [akai-katto/dandere2x#212]
Hello, I will tell you about my experience with Dandere2x.

I have used this program to rescale my favorite series, because I like it the most. My computer is not very powerful and this is the best application I have found. I use it for a very ambitious project (not for profit), which I have been working on for 1 year.

I have seen that with the new version 3.3, they have finally fixed the bug of dark blocks in transitions, which I have seen since I have known the program.

I am currently using version 3.0.3b of Dandere2x, it is the one that suits me best, because it is the one with less bugs.

I use it because it is the one that solved several problems that came since 1.9, it is the one in which the grid is less visible, because in 3.1 and higher, it is more noticeable again.

3.3 keeps the grid by precision (that is, when the block moves a little and takes it as if it were the same, making that distortion).
3.0.3
![image](https://user-images.githubusercontent.com/72674815/124374137-ba947b00-dc66-11eb-9917-4b0815170ec4.png)
3.3
![image](https://user-images.githubusercontent.com/72674815/124374128-a6507e00-dc66-11eb-9c89-e5be12900560.png)

This is the dark blocks bug (it was fixed in 3.3 Fade disabled)
3.0.3
![image](https://user-images.githubusercontent.com/72674815/124374151-d5ff8600-dc66-11eb-8273-574970a7c297.png)
3.3
![image](https://user-images.githubusercontent.com/72674815/124374160-e879bf80-dc66-11eb-9ef6-bf131aa2b856.png)

This is the grid in 3.0.3, the one you always see (it was corrected in 3.3).
![image](https://user-images.githubusercontent.com/72674815/124393772-0a585e00-dcca-11eb-8a08-125df4ef8bd5.png)

I would like that this problem could be solved in the latest versions.

**Comment by akai-katto** [comment]
Thanks for bringing this up, I'm looking at it now (I appreciate your work in the past, I had to take a hiatus from dandere2x due to life issues but I'm back at it). Your information regarding 3.0.2b and 3.3 having different block matching gives me a starting point of knowing what bugs to fix, so I can look into this. I'll report back to this thread when I found anything + let me know if you find anything else.

**Comment by CareBearsAICAL** [comment]
@akai-katto Thank you very much, I have updated the previous message a bit.
It turns out that 3.0.3b has a grid that is noticeable in light colors as the squares are maintained. That doesn't happen in 3.3, but there are slight glitches in 3.3 that sometimes clear lines are generated between blocks. But that also happens in 3.0.3b, but not in the same way, which must be the same that is generated in the previous image that I applied the difference effect between 3.3 and 3.0.3 of Care Bears logo (that grid is from 3.0.3).

3.0.3
![image](https://user-images.githubusercontent.com/72674815/124395092-3080fc80-dcd0-11eb-88fe-607fc7071b8d.png)
It is not very noticeable, but it is very noticeable when I lower the saturation of the video.

In 3.3, I did a test at 10px blocks to see how it looked, and if you noticed a grid a little difficult to explain. You don't notice lines as such, but there is a grid effect when there are movements.

**Comment by akai-katto** [comment]
> 
> 
> @akai-katto Thank you very much, I have updated the previous message a bit.
> It turns out that 3.0.3b has a grid that is noticeable in light colors as the squares are maintained. That doesn't happen in 3.3, but there are slight glitches in 3.3 that sometimes clear lines are generated between blocks. But that also happens in 3.0.3b, but not in the same way, which must be the same that is generated in the previous image that I applied the difference effect between 3.3 and 3.0.3 of Care Bears logo (that grid is from 3.0.3).
> 
> 3.0.3
> ![image](https://user-images.githubusercontent.com/72674815/124395092-3080fc80-dcd0-11eb-88fe-607fc7071b8d.png)
> It is not very noticeable, but it is very noticeable when I lower the saturation of the video.
> 
> In 3.3, I did a test at 10px blocks to see how it looked, and if you noticed a grid a little difficult to explain. You don't notice lines as such, but there is a grid effect when there are movements.

What block size is this running at? I think this may be the case when block-size is too low, but I can't say for sure.

**Comment by CareBearsAICAL** [comment]
Oops, I think 3.3 still has this bug of dark blocks, but to a lesser extent (this bug occurs in fade transitions, it's like to identify blocks not taking into account the brightness, but the change of colors) (this can be seen more when using small blocks, I use b60 to avoid this error, but sometimes it is unavoidable).
![image](https://user-images.githubusercontent.com/72674815/124395567-d3d31100-dcd2-11eb-9977-80abcbb329ee.png)
in all my tests I use these configurations
![image](https://user-images.githubusercontent.com/72674815/124395612-109f0800-dcd3-11eb-945f-1f7a60ebc857.png)
(maximum image quality (99 or 100))

**Comment by akai-katto** [comment]
Can you upload the video (send it to me over reddit if you want it to be private https://www.reddit.com/user/akai_katto) so I can see if disabling "fade" fixes this? It may be the case that some people may have to disable some of the "tricks" i use for dandere2x, something I would be happy to support.

**Comment by CareBearsAICAL** [comment]
@akai-katto Here are some tests I have done
https://drive.google.com/drive/folders/1SyDXGCGorVwhDuFfrATO25yoA7jmZNu3?usp=sharing

**Comment by CareBearsAICAL** [comment]
@akai-katto I also added the Outro in which the bug of the dark blocks is noticeable.

**Comment by CareBearsAICAL** [comment]
@akai-katto Ready, I added the videos for the tests.

**Comment by akai-katto** [comment]
I've uploaded dandere2x_cpp with fade disabled, it seems to  have fixed the issue:

https://github.com/akai-katto/dandere2x/releases/download/3.3/dandere2x_cpp_no_fade.zip

Replace this with the dandere2x_cpp.exe in your "externals" folder.

**Comment by CareBearsAICAL** [comment]
@akai-katto Thanks a lot, now I can patch some parts of 3.0.3b videos with the modified 3.3. I have to wait for a better way to fix the grid. I base myself with that base video that I had uploaded to see the differences of each version.
The 3.0.3 still has a quite noticeable grid failure in clear parts and in the 3.3 it has nothing. But the 3.3 in some parts suddenly appears grid. I hope that the base video can be useful for you because it is the only one in which I have seen this failure in a noticeable way. With a block 60 and image quality 100 you can see above the moon, which is like a flicker, you would only have to make that does not happen and the problem would be solved.
