### ISSUE TITLE
Grid in 3.0.3 vs. 3.3 (solved in 3.6)

### ISSUE THREAD

**Issue by CareBearsAICAL** [akai-katto/dandere2x#213]
Here are the differences between the grid in Dandere2x 3.0.3b vs [3.1-3.3]

Test 1: Lines from time to time
3.0.3 | 3.3
![image](https://user-images.githubusercontent.com/72674815/124399469-b9f0f880-dce9-11eb-8355-bba5195e12e0.png)![image](https://user-images.githubusercontent.com/72674815/124399548-1e13bc80-dcea-11eb-90d4-3a3517dfd68a.png)
3.0.3b: It looks dirtier but with less noticeable grid. | 3.3: Looks cleaner but with a much more noticeable grid

Test 2: Corners
3.0.3 | 3.3
![image](https://user-images.githubusercontent.com/72674815/124399704-36380b80-dceb-11eb-93a8-d30303b9a7e3.png)![image](https://user-images.githubusercontent.com/72674815/124399693-24eeff00-dceb-11eb-9351-d7451977b9a8.png)
3.0.3b: Looks dirtier but almost no corners visible | 3.3b: Much better quality but has clear corners.

Test 3: Differences between clear blocks
3.0.3b | 3.3 | Diference
![image](https://user-images.githubusercontent.com/72674815/124399910-c296fe00-dcec-11eb-80a4-0c6700c1d540.png)![image](https://user-images.githubusercontent.com/72674815/124399912-c4f95800-dcec-11eb-844a-cf39baa064ea.png)![image](https://user-images.githubusercontent.com/72674815/124399913-c591ee80-dcec-11eb-9a4f-61730037f29a.png)
3.0.3b: Edge flaws clearly visible | 3.3: No edge flaws are visible

With this file I hope that tests can be done, making the error of test 1 disappear.
https://drive.google.com/file/d/1rejyqKqZxspWLLLIi-QXKPp-glOiXSNN/view?usp=sharing

**Comment by akai-katto** [comment]
Out of curiosity, do you prefer 3.0.3b's dirtiness? The origin of it is I have an algorithm to "clean up" those spots that are present in 3.3, but add to the dirtiness. 

Since dandere2x_cpp is more customizable, I can allow users to fine tune what settings they want now (i.e you don't want fade on for your videos), so this is something I'll try adding.

**Comment by CareBearsAICAL** [comment]
It is difficult to choose.
There are two types of grids, in 3.0.3b the grid in general is much less visible. But the light colored grid is very visible. In 3.3 the grid in general is more visible, but in light colors it is not visible.

In both versions there are the clear lines, I believe in equal measure, but in different locations. Because in the Test I sent, it was only noticeable in 3.3, but 3.0.3b also has the same error, but in other parts, as here it appeared to me in a flat color.
3.0.3b
![image](https://user-images.githubusercontent.com/72674815/124779859-1d5c6f80-df10-11eb-98ad-870bda9449ca.png)
The algorithm disguises a little the general grid, leaving it less visible, but I don't like very much the idea that it messes up the image and generates grid in light colors.

I think that for now we have to look for another solution to eliminate those lines and corners that sometimes are generated. Because these are in both versions. I think that for now it should be kept that 3.3 is clean, to be able to appreciate the lines well and to be able to correct it. Maybe increasing the precision of the blocks, so that they change more often and see the lines and corners.

**Comment by CareBearsAICAL** [comment]
@akai-katto On second thought, for now, I'd like a version of 3.3 with that "dirt" from 3.0.3b, because what I'm doing is using 3.0.3b for rescaling and 3.3.1 for patching. I think a version like that would make my job a lot easier.
