### ISSUE TITLE
The Grid (Again) in Yellow colours (Read Please :c)

### ISSUE THREAD

**Issue by CareBearsAICAL** [akai-katto/dandere2x#216]
The error happens mostly in clear places and are clearly visible, manually editing this has slowed me down a lot, I just hope it can be fixed soon.

Here I leave the video in both versions.
You can notice from timestamp 05:45 - 06:25

3.0.3b
https://drive.google.com/file/d/1_HOfcfplRMIH0IbC5FeMfwZj416y8dab/view?usp=sharing
3.3.1
https://drive.google.com/file/d/10qm-9PhMvD_IKbAr5gYrfrRzRy59CVfA/view?usp=sharing

File for testing [7 seconds]
https://drive.google.com/file/d/1bWrfAZCbLRSwQbqwWVn4_8dF5-AgKSCy/view?usp=sharing

In general, sometimes it is more noticeable in 0.3.0b and sometimes in 3.3.1, sometimes it is not seen in 3.3.1, but the problem occurs in the same way in both versions.

It may not look like much in pictures, but the problem is that in the video it flickers and anyone can see it.

3.0.3b:
![image](https://user-images.githubusercontent.com/72674815/128263665-3a464d8c-5be0-45ed-b9ba-79a3ebd1a2e5.png)
![image](https://user-images.githubusercontent.com/72674815/128263667-d44a353b-184e-403b-96d4-f87778a2440d.png)
![image](https://user-images.githubusercontent.com/72674815/128263668-583220f0-34de-4175-83a1-d4f954cb3313.png)
![image](https://user-images.githubusercontent.com/72674815/128263671-e3ee4965-8ab6-4b3b-89a4-734e91a65d9d.png)

3.3.1:
![image](https://user-images.githubusercontent.com/72674815/128263831-d877ab94-998c-4eff-8094-921ec887d06e.png)
![image](https://user-images.githubusercontent.com/72674815/128263832-05722ae9-a836-40e5-b6fb-892e29e5cf7b.png)
![image](https://user-images.githubusercontent.com/72674815/128263834-293a4452-7ff6-4e14-b48f-46c24f7d8504.png)
![image](https://user-images.githubusercontent.com/72674815/128263836-a10ac092-5eab-414a-bb94-82770793a8c9.png)

**Comment by akai-katto** [comment]
Hi, 

Sorry for not responding, life has taken over and i've been unable to be active due to life circumstances taking over. Please leave the google drive files open, and when I finish moving cities (in the process) I'll take a look at it. I'm hoping for life to slow down once I move into my new home.

**Comment by akai-katto** [comment]
Hello, just following up.

I've been dealing with health issues, but things are clearing up. Just letting you know I'm aware of my absence and feeling good about returning to working on dandere2x more often.

**Comment by akai-katto** [comment]
I'll start working on this now.. the realSR changes haven't been used that much, and returning back to fixing the color issues.
