### ISSUE TITLE
GUI says "Upscaling in progress" but terminal shows error

### ISSUE THREAD

**Issue by Caticer** [akai-katto/dandere2x#218]
Terminal:
![image](https://user-images.githubusercontent.com/25691875/130053137-883fe349-7c79-4292-9d0c-c6415b2e9bec.png)

Here the error line:
`config file: multiprocess
Traceback (most recent call last):
  File "gui_driver.py", line 181, in press_upscale_button
FileNotFoundError: [Errno 2] No such file or directory: 'config_files/output_options.yaml'`

And gui:
![image](https://user-images.githubusercontent.com/25691875/130053090-d8461d6f-8f85-4c8b-a613-0b8f0a0fd410.png)

**Comment by akai-katto** [comment]
Sorry for taking so long to respond, have been dealing with health concerns.


The executable needs to be kept in the original location (when you download the file, it needs to be kept with it's respective files, such as the config yaml) in order to properly work.

**Comment by Caticer** [comment]
I hope you are fine. Thanks
