### ISSUE TITLE
4x upscaling with Waifu2x-Vulkan

### ISSUE THREAD

**Issue by Naizuri77** [akai-katto/dandere2x#223]
The latest versions of waifu2x-ncnn-vulkan support more upscaling factors than 2x (1/2/4/8/16/32), so I was wondering if the GUI could be updated in the future to also allow 4x upscaling? It's not something extremely necessary so I would understand focusing on more important issues over this, but it would be a nice addition to have.

**Comment by akai-katto** [comment]
Thanks for the headsup. Thanks naizuri.


(I'm slowly getting more active again with the dandere2x project)

**Comment by akai-katto** [comment]
added
