### ISSUE TITLE
Aspect ratio and dvd videos

### ISSUE THREAD

**Issue by eoiz** [akai-katto/dandere2x#233]
Hi, I'm trying to upscale some dvd-mkv's. But every file I upscale turn out to change the aspect ratio (deforming the video from 16/9 to 3/2).
The problem I think I understood is the pixel aspect ratio, any suggestion to how to resolve this?

Thanks, and sorry for bad english :D

**Comment by gurkenjaeger13** [comment]
I am not sure if this could help but maybe you can try to reencode them with for example makemkv?

**Comment by eoiz** [comment]
I tried that, but hasn't worked...for now I'm re-encoding videos with StaxRip wich let you change the aspect ratio...would be nice avoid that extra encoding :/

**Comment by linckandrea** [comment]
If your video is in a .mkv container you can enforce its aspect ratio trough MKVToolNix GUI.

**Comment by eoiz** [comment]
@linckandrea sorry for the late response but actually that fixed it! Really nice! Thanks you!
