### ISSUE TITLE
AssertionError: C:\Users\username\Downloads\3.5\3.5\externals\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan.exe does not exist!

### ISSUE THREAD

**Issue by gurkenjaeger13** [akai-katto/dandere2x#239]
Hi, this is my first time using the dandere2x upscaler.

I downloaded the "3.5.zip" and extracted it in my downloads folder. I started the upscaling and it all worked flawlessly. It also went very fast (ca 70fps). Everything went smooth up until one point. Then the program stopped and showed the following error:

**`Exception in thread Thread-1:`**
**`Traceback (most recent call last):`**
`  File "threading.py", line 954, in _bootstrap_inner`
`  File "dandere2x\__init__.py", line 57, in run`
`  File "dandere2x\dandere2x_service\service_types\multiprocess_service.py", line 61, in run`
`  File "dandere2x\dandere2x_service\service_types\multiprocess_service.py", line 58, in _pre_process`
`  File "dandere2x\dandere2x_service\__init__.py", line 81, in __init__`
`  File "dandere2x\dandere2x_service\core\waifu2x\waifu2x_ncnn_vulkan.py", line 40, in __init__`
**`AssertionError: C:\Users\username\Downloads\3.5\3.5\externals\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan.exe does not exist!`**

In the "3.5/workspace/gui" folder there are currently 3 video files (called: "_split_video0.mkv_", "_split_video1.mkv_", "_split_video2.mkv_"). Combined, they would show the whole video I wanted to upscale. I can watch them in VLC (NOT in Windows "Photos" etc.) but the time at the bottom always says 00:00 and also the file properties seem to be completely missing (no resolution etc., only shows "0 kbps").

I hope I didn't miss anything but I have no idea how to fix this error.

**Comment by eoiz** [comment]
Have you downloaded the externals?
You do it by clicking download externals on top right of dandere2x gui.

**Comment by gurkenjaeger13** [comment]
You were right! I really thought I had already clicked it but turns out I didn't. I left my computer on it for the whole day and I was able to upscale a whole episode (23min)! Looks fantastic!
Thank you very much for the quick help!
By the way I would be interested in learning a bit more about what steps this upscaler follows (like: 1. Creating temp files, 2. Reading metadata, etc.). Do you know if there is any documentation like that?
