### ISSUE TITLE
get_list_from_file_and_wait: permission error on file | many permission errors (ca. 1 PER FRAME!)

### ISSUE THREAD

**Issue by freshefisch** [akai-katto/dandere2x#241]
I don't know why I get so many permission errors. The video still gets properly upscaled but I feel like it is slowing it down by a lot. (I ran as administrator.) I ran the included video (copied.mkv) on my brothers PC and on mine. (He has 3060ti and Ryzen 5, I have 2080super and Ryzen 9.) **He didn't get ANY permission errors!** Also, his total time was more than **twice as fast!** Does anyone know how I can fix the permission errors?
(I also get a lot of syntax errors, sometimes 10 at a time but then none for a long time)

Red - Permission Errors
Blue - Upscaling
![InkedScreenshot 2022-01-31 192127_LI](https://user-images.githubusercontent.com/62943210/151852088-448bb143-2f46-4455-9bc1-52b913e76037.jpg)

**Comment by eoiz** [comment]
Have you tried to run Dandere2x with administrator privileges?

**Comment by eoiz** [comment]
Maybe try to move the dandere2x folders...like in the C app folder (and run as admin like you do now).

**Comment by gurkenjaeger13** [comment]
> Maybe try to move the dandere2x folders...like in the C app folder (and run as admin like you do now).

I tried that right now but I still get pretty much the same amount of permission errors...

Could it have anything to do with like my Antivirus (Bitdefender)?

<img width="1081" alt="Screenshot 2022-01-31 214011" src="https://user-images.githubusercontent.com/62943210/151869805-165de68b-66b4-400a-9858-629350b00e81.png">

**Comment by gurkenjaeger13** [comment]
UPDATE: I found a very simple way to get around this problem, which also sped up the upscaling BY TWO TIMES (at least for me)!
**The solution was to run the program in POWERSHELL**. 
I just followed this official Reddit post from a year ago: https://www.reddit.com/r/Dandere2x/comments/ims85s/feedback_needed_for_those_having_permission/
Tutorial: https://imgur.com/a/beiaBqk
______________________________
What is very interesting is that after running the program once in powershell I get no permission errors anymore in cmd and it is about the same speed (before it was about 2 times slower)
______________________________
I rendered the test video (copied.mkv) on multiple setups:
- 3060ti and Ryzen 5: IN CMD: Ca 3.5 min, **no permission errors**
- 2080super and Ryzen 9: IN CMD: Ca 8 min, A LOT OF PERMISSION ERRORS (ca 1 per frame)
- 2080super and Ryzen 9: IN POWERSHELL: Ca 3 min, ZERO PERMISSION ERRORS!
- **2080super and Ryzen 9: IN CMD AFTER RUNNING POWERSHELL ONCE: Ca. 2.2 min, ZERO PERMISSION ERRORS!**

**Comment by gurkenjaeger13** [comment]
I will try a 25 minute video tomorrow and see how long it takes and if I still get no permission errors. Today I did a 25 minute video WITH many permission errors and it took about 13 hours.
