### ISSUE TITLE
Do not upscale more than 13 mins!

### ISSUE THREAD

**Issue by DCGYT** [akai-katto/dandere2x#257]
Does not remaster more than 13 minutes MKV (3.6)

Hi, I wanted to do a second remastering to my project using the full clips.

I have tried upscaling a 22 minute video, but when I complete the process, only 13 minutes of the clip is visible.

Checking the log only shows that only **13 minutes** of frames were upscaled.

This only happens when I use an **MKV file**, more precisely, I use the avidemux software before using Dandere2x, because I can sharpen the video and get better results.

When I export in avidemux in MP4, Dandere2x upscales the video completely, but my editing program afterwards does not take the frames correctly (DaVinci Resolve).

When I used MKV files, Dandere2x exported it to MKV and DaVinci Resolve used the clip at 23.976FPS which is correct, but when using an MP4 clip, Dandere2x exports it in MKV but the program identifies it as 24FPS which is not right, generating inconsistency in the frames.

Here is the file I tried to upscale. It is exported in Mpeg4 AVC (x264) in MKV:
https://drive.google.com/file/d/1uvQR4mvx9xM_kG3e2UiO1eV1NV7chTXF/view?usp=sharing

(before I tried with x265 but the result was the same)

I will be attentive to an answer, because I will not be able to advance.
And this version has fixed the grid bug, being a great advance and they have done a great job, the vertical lines error can pass because it is not so noticeable and the color can be tried to fix with editing software, but I would like to have the complete clips, so I could save enough disk space and optimize more the video project files.

Here is on a notepad what I had printed on the console.
https://drive.google.com/file/d/1rNagrkSacb5w9e271kbFcjWWMbyFdLrK/view?usp=sharing

Edit: I'd better make a video and show everything.

**Comment by markswam** [comment]
I'm having a similar issue. I'm trying to upscale a couple animated films in MKV format but they all stop processing after ~15-20 minutes.

**Comment by akai-katto** [comment]
Thanks for reporting, sorry I was on vacation when you reported this. I'll be taking a look at it.

**Comment by DCGYT** [comment]
@akai-katto I understand you, well then, let's wait xd. I would like to do a second remastering of my favorite series, but I'll be waiting for Dandere2x not to have a time limit and the colors to be maintained, because the latter still affects me a lot, because the series does not convey the same feeling as before with the change of color palette. Still take it easy, I know that doing this can be exhausting.

**Comment by akai-katto** [comment]
Can you upload the original files? I'm trying to look into this, I need a reference file to replicate the issue.
