### ISSUE TITLE
Small residual_images queue

### ISSUE THREAD

**Issue by eoiz** [akai-katto/dandere2x#260]
I can't find any way to force Dandere2x to fill up more the residual_images folder: is there any way It can prepare more than 95 images to upscale?
I think that it would be nice to have a bigger queue for the GPU...

**Comment by akai-katto** [comment]
I'll add it to the config in the next release

**Comment by akai-katto** [comment]
https://github.com/akai-katto/dandere2x/releases/tag/3.7
