### ISSUE TITLE
Support with Intel graphics

### ISSUE THREAD

**Issue by OyewoleOyedeji** [akai-katto/dandere2x#262]
I would like to ask if this project has support for Intel graphics card like the HD, UHD and Iris Xe, series. Because from everything I'm seeing the project only supports Nvidia cards

**Comment by akai-katto** [comment]
It works on my uhd630. Does it not work for you?

**Comment by OyewoleOyedeji** [comment]
No it doesn't, please could you provide the steps you used to make it work. Thanks 👍

**Comment by akai-katto** [comment]
Can you provide the error message that you're running into, or a screenshot / recording of what you're having issues with? I followed the same process as I do for my windows build

**Comment by OyewoleOyedeji** [comment]
I have an Intel only PC with no Nvidia card. Just the UHD integrated graphics.

**Comment by akai-katto** [comment]
I have no issues still running it, can you describe what issues you're running into?

**Comment by eoiz** [comment]
@akai-katto just for curiosity: will it help speed to use both DGPU and IGPU?
And will it be possible to use multiple gpus like sli or so?

**Comment by OyewoleOyedeji** [comment]
Never mind, I'll find another project that works for me
