### ISSUE TITLE
Multiprocess video segment order reversed

### ISSUE THREAD

**Issue by kmhcreative** [akai-katto/dandere2x#265]
I installed Dandere2x via Homebrew on my M1 Mac and when I select "Multiprocess" it reassembles the split video segments in the reverse order.  The "split_video" MKV files are in the right order, but the "subworkspace" folders and "non_migrated" MKV files are in the wrong order.

I fixed this by editing the _/dandere2x/dandere2x_service/service_types/multiprocess_service.py_ file line 42:

`        divided_re_encoded_videos = sorted(glob.glob(os.path.join(self._service_request.workspace, "*.mkv")))`

That literally has it sorted.  The segments now reassemble in the correct order.

**Comment by akai-katto** [comment]
Would you mind making a PR for this so you can get credit, or would you want me to do this?

**Comment by kmhcreative** [comment]
I don't need credit, a PR seems like overkill for a single word and two parentheses.

**Comment by akai-katto** [comment]
closed.

Sorry for the slow close, ran into a medical emergency.
